'use client';

import { useMemo, useState } from 'react';

import { CopyLinkButton } from './PromoterShareActions';

const channels = ['Instagram', 'WhatsApp', 'Snapchat', 'Email', 'Bio link', 'Poster QR', 'Custom'] as const;

export function PromoterLinkBuilder() {
  const [eventId, setEventId] = useState('neon-nights');
  const [channel, setChannel] = useState<(typeof channels)[number]>('Instagram');
  const [label, setLabel] = useState('Main story');
  const [draftReady, setDraftReady] = useState(false);
  const [preparing, setPreparing] = useState(false);
  const [shared, setShared] = useState(false);
  const slug = useMemo(() => `${eventId}-${channel.toLowerCase().replace(/\s+/g, '-')}`, [channel, eventId]);
  const previewUrl = `c1rcle.in/zoya/${slug}`;
  const caption = `Meet me at ${eventId === 'neon-nights' ? 'Neon Nights' : 'Bassline Nights'} — tickets via my C1RCLE link.`;

  const prepare = () => {
    if (preparing || !label.trim()) return;
    setPreparing(true);
    window.setTimeout(() => { setDraftReady(true); setPreparing(false); }, 500);
  };

  const share = async () => {
    const data = { title: 'THE C1RCLE event link', text: caption, url: `https://${previewUrl}` };
    if (typeof navigator.share === 'function') await navigator.share(data);
    else await navigator.clipboard.writeText(`${caption} https://${previewUrl}`);
    setShared(true);
    window.setTimeout(() => { setShared(false); }, 1800);
  };

  return (
    <section className="promoter-link-builder pd-surface">
      <div className="promoter-link-builder-copy"><span>Tracked campaign</span><h2>Turn any share into measurable ticket movement.</h2><p>Select an event and channel. The backend will issue the authoritative tracking link; this frontend currently prepares and previews the campaign request.</p></div>
      <div className="promoter-link-form">
        <label><span>Linked event</span><select value={eventId} onChange={(event) => { setEventId(event.target.value); setDraftReady(false); }}><option value="neon-nights">Neon Nights</option><option value="bassline-nights">Bassline Nights</option></select></label>
        <label><span>Campaign channel</span><select value={channel} onChange={(event) => { setChannel(event.target.value as (typeof channels)[number]); setDraftReady(false); }}>{channels.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label><span>Campaign label</span><input value={label} onChange={(event) => { setLabel(event.target.value); setDraftReady(false); }} maxLength={40} /></label>
        <button type="button" onClick={prepare} disabled={!label.trim() || preparing}>{preparing ? 'Preparing…' : 'Prepare tracked-link request'}</button>
      </div>
      {draftReady ? <div className="promoter-campaign-output" aria-live="polite">
        <div className="promoter-story-preview promoter-tone promoter-tone--orange"><span>THE C1RCLE · {channel}</span><strong>{eventId === 'neon-nights' ? 'NEON NIGHTS' : 'BASSLINE NIGHTS'}</strong><small>{label}</small><b>GET TICKETS ↗</b></div>
        <div className="promoter-qr-preview" aria-label="Decorative QR placement preview"><span>QR</span><div>{Array.from({ length: 36 }, (_, index) => <i key={String(index)} className={index % 3 === 0 || index % 7 === 0 ? 'is-dark' : undefined} />)}</div><small>Authoritative QR generated by link API</small></div>
        <div className="promoter-campaign-actions"><span>Request preview</span><strong>{previewUrl}</strong><small>{channel} · {label}</small><blockquote>{caption}</blockquote><div><CopyLinkButton value={`https://${previewUrl}`} /><CopyLinkButton value={caption} label="Copy caption" /><button type="button" className="promoter-copy-button" onClick={() => { void share(); }}>{shared ? 'Shared' : 'Share campaign'}<span aria-hidden="true">↗</span></button><button type="button" className="promoter-copy-button" disabled title="Download activates after the backend issues the authoritative QR">Download QR</button></div></div>
      </div> : null}
    </section>
  );
}
