'use client';

/**
 * Thin adapter that lets the ported venue screens reference icons by the same
 * kebab-case names the design mockup used (`<i data-lucide="door-open">`),
 * resolved against the shared `@c1rcle/icons` surface.
 */

import {
  AccountIcon,
  AddIcon,
  AdvancedSetupIcon,
  AnnouncementIcon,
  ApprovedIcon,
  ArchiveIcon,
  BackIcon,
  BankIcon,
  BatteryIcon,
  BottleServiceIcon,
  CalendarIcon,
  CheckIcon,
  CheckedIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  CloseIcon,
  DeleteIcon,
  DisconnectIcon,
  DoorModeIcon,
  DragHandleIcon,
  EditIcon,
  EmailIcon,
  EmptyDateIcon,
  ExpandIcon,
  ExportIcon,
  FavouriteIcon,
  ForwardIcon,
  GalleryViewIcon,
  GuestIcon,
  GuestPortalIcon,
  ImageIcon,
  IncidentIcon,
  InfoIcon,
  InviteIcon,
  LinkIcon,
  ListViewIcon,
  LocationIcon,
  LockedIcon,
  MarkUnreadIcon,
  MicIcon,
  MobileAppIcon,
  NextIcon,
  NoteIcon,
  NotificationIcon,
  OpenInPlaceIcon,
  OrderIcon,
  PartnerIcon,
  PendingIcon,
  PhoneIcon,
  PinIcon,
  PreviousIcon,
  PublishIcon,
  RatingIcon,
  RefreshIcon,
  RefundIcon,
  RejectedIcon,
  ReplyIcon,
  RequestPayoutIcon,
  RowActionsIcon,
  ScanIcon,
  ScheduledPayoutIcon,
  SearchIcon,
  SendIcon,
  SignalIcon,
  SmsIcon,
  SortableIcon,
  TicketIcon,
  TimeIcon,
  TrendUpIcon,
  UnderConstructionIcon,
  UncheckedIcon,
  UsersIcon,
  VideoIcon,
  VisibleIcon,
  WarningIcon,
  WhatsAppIcon,
  WifiIcon,
  WithdrawIcon,
  AdminIcon,
} from '@c1rcle/icons';

import type { IconProps as LucideIconProps } from '@c1rcle/icons';
import type { ComponentType, CSSProperties } from 'react';

const REGISTRY: Record<string, ComponentType<LucideIconProps>> = {
  archive: ArchiveIcon,
  'arrow-down-to-line': WithdrawIcon,
  'arrow-left': BackIcon,
  'arrow-right': ForwardIcon,
  'arrow-up-right': OpenInPlaceIcon,
  'battery-full': BatteryIcon,
  bell: NotificationIcon,
  'building-2': PartnerIcon,
  calendar: CalendarIcon,
  'calendar-check': ScheduledPayoutIcon,
  'calendar-clock': RequestPayoutIcon,
  'calendar-plus': EmptyDateIcon,
  check: CheckIcon,
  'check-circle-2': ApprovedIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': PreviousIcon,
  'chevron-right': NextIcon,
  'chevron-up': ChevronUpIcon,
  'chevrons-up-down': SortableIcon,
  'circle-user': AccountIcon,
  'clipboard-list': IncidentIcon,
  clock: TimeIcon,
  'door-open': DoorModeIcon,
  download: ExportIcon,
  eye: VisibleIcon,
  globe: GuestPortalIcon,
  'grip-vertical': DragHandleIcon,
  hammer: UnderConstructionIcon,
  heart: FavouriteIcon,
  hourglass: PendingIcon,
  image: ImageIcon,
  info: InfoIcon,
  landmark: BankIcon,
  'layout-grid': GalleryViewIcon,
  link: LinkIcon,
  list: ListViewIcon,
  lock: LockedIcon,
  mail: EmailIcon,
  'mail-open': MarkUnreadIcon,
  'map-pin': LocationIcon,
  'maximize-2': ExpandIcon,
  megaphone: AnnouncementIcon,
  'message-circle': WhatsAppIcon,
  'message-square': SmsIcon,
  mic: MicIcon,
  'more-horizontal': RowActionsIcon,
  'party-popper': PublishIcon,
  pencil: EditIcon,
  phone: PhoneIcon,
  pin: PinIcon,
  plus: AddIcon,
  power: DisconnectIcon,
  receipt: OrderIcon,
  'refresh-cw': RefreshIcon,
  reply: ReplyIcon,
  'rotate-ccw': RefundIcon,
  'scan-line': ScanIcon,
  search: SearchIcon,
  send: SendIcon,
  shield: AdminIcon,
  signal: SignalIcon,
  'sliders-horizontal': AdvancedSetupIcon,
  smartphone: MobileAppIcon,
  square: UncheckedIcon,
  'square-check': CheckedIcon,
  star: RatingIcon,
  'sticky-note': NoteIcon,
  ticket: TicketIcon,
  'trash-2': DeleteIcon,
  'trending-up': TrendUpIcon,
  'triangle-alert': WarningIcon,
  user: GuestIcon,
  'user-plus': InviteIcon,
  users: UsersIcon,
  video: VideoIcon,
  wifi: WifiIcon,
  wine: BottleServiceIcon,
  x: CloseIcon,
  'x-circle': RejectedIcon,
};

export interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: CSSProperties;
  className?: string;
}

export function Icon({ name, size = 16, color, style, className }: IconProps) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return (
    <Cmp
      size={size}
      {...(color ? { color } : {})}
      {...(className ? { className } : {})}
      style={{ flex: 'none', ...style }}
    />
  );
}
