import type { Brand } from './primitives.js';

/**
 * Correlates a frontend request with a backend log line. Generated by
 * `@c1rcle/api-client` and sent as `x-request-id` on every call.
 */
export type RequestId = Brand<string, 'RequestId'>;

/**
 * The closed set of failure categories the frontend can meaningfully react to.
 *
 * These are transport- and contract-level concerns, deliberately not domain
 * errors: the frontend does not own business rules, so it does not enumerate
 * business failures. Anything the backend reports beyond this set arrives as
 * `unknown` with its original message preserved.
 */
export type ApiErrorCode =
  | 'network'
  | 'timeout'
  | 'aborted'
  | 'unauthorized'
  | 'forbidden'
  | 'not_found'
  | 'conflict'
  | 'validation'
  | 'rate_limited'
  | 'server'
  | 'parse'
  | 'unknown';

export interface ApiError {
  readonly code: ApiErrorCode;
  readonly message: string;
  readonly status: number | undefined;
  readonly requestId: RequestId | undefined;
  /** Field-level messages, when the backend reports a validation failure. */
  readonly fieldErrors: Readonly<Record<string, readonly string[]>> | undefined;
}

export interface PageInfo {
  readonly page: number;
  readonly pageSize: number;
  readonly total: number;
  readonly hasNextPage: boolean;
}

export interface Paginated<T> {
  readonly items: readonly T[];
  readonly pageInfo: PageInfo;
}
