// GENERATED by C1RCLE-BACKEND/scripts/export-contracts.mjs — do not edit. Source: packages/contracts/src/contracts/admin-promoters.ts
import { z } from 'zod';

import { opaqueIdSchema, paginatedSchema } from './shared.js';

/**
 * ─── Phase 7 admin promoters desk DTOs ───────────────────────────────────────
 * V2 has no standalone "promoter" entity — a promoter is an `Organization`
 * member with a versioned commission assignment per event
 * (`PromoterAssignment`). Platform-wide, read-only listing for the
 * `/promoters` admin dashboard.
 */
export const adminPromoterAssignmentStatusSchema = z.enum(['active', 'ended', 'suspended']);
export type AdminPromoterAssignmentStatus = z.infer<typeof adminPromoterAssignmentStatusSchema>;

export const adminPromoterAssignmentDtoSchema = z.object({
  id: opaqueIdSchema,
  eventId: opaqueIdSchema,
  promoterId: opaqueIdSchema,
  status: adminPromoterAssignmentStatusSchema,
  ratePercent: z.number().nonnegative(),
  flatPaise: z.number().int().nonnegative(),
  createdAt: z.iso.datetime(),
  endedAt: z.iso.datetime().nullable(),
  suspendedAt: z.iso.datetime().nullable(),
});
export type AdminPromoterAssignmentDto = z.infer<typeof adminPromoterAssignmentDtoSchema>;

export const adminPromoterAssignmentListResponseSchema = paginatedSchema(
  adminPromoterAssignmentDtoSchema,
);
export type AdminPromoterAssignmentListResponse = z.infer<
  typeof adminPromoterAssignmentListResponseSchema
>;

/* ─── Promoter lifecycle (suspend / reinstate) ─────────────────────────────── */

export const adminPromoterSuspendRequestSchema = z.object({
  reason: z.string().min(1).max(500).optional(),
});
export type AdminPromoterSuspendRequest = z.infer<typeof adminPromoterSuspendRequestSchema>;

export const adminPromoterActionResponseSchema = z.object({
  promoterId: opaqueIdSchema,
  action: z.enum(['suspended', 'reinstated']),
  affectedAssignments: z.number().int().nonnegative(),
  at: z.iso.datetime(),
});
export type AdminPromoterActionResponse = z.infer<typeof adminPromoterActionResponseSchema>;
